version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # 루트 비밀번호 설정
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      - mariadb

volumes:
  db_data:
